# Este modelo do AWS SAM foi gerado a partir da configuração da sua função. Se sua
# função tiver um ou mais gatilhos, observe que os recursos da AWS associados a
# esses gatilhos não estão totalmente especificados neste modelo e incluem valores
# de espaço reservado. Abra este modelo no AWS Infrastructure Composer ou no seu
# IDE favorito e modifique-o para especificar um aplicativo sem servidor com
# outros recursos da AWS.
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  ArthurMercadoLivre:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Description: ''
      MemorySize: 128
      Timeout: 3
      Handler: lambda_function.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:us-east-1:199299155478:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:us-east-1:199299155478:log-group:/aws/lambda/Arthur_MercadoLivre:*
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /Arthur_MercadoLivre
            Method: ANY
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
